version: '3.8'

services:
###############################################################################
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile           # custom image to build passwd file
    container_name: mosquitto
    restart: unless-stopped
    env_file: .env                     # inject all variables
    ports:
      - "1883:1883"                    # MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/broker/uptime", "-h", "localhost", "-C", "1"]
      interval: 30s
      timeout: 5s
      retries: 3

###############################################################################
  router:                               # ← your Go or Python MQTT client
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: mqtt-router
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/app/config:ro         # devices.json, etc.
      - ./AWS_Certificates:/app/certs:ro
